name: build-spdx
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    if: contains(github.event.comment.body, '/scan')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Running tern action for spdx output.`
            })
      - uses: philips-labs/tern-action@update-versions
        id: scan
        with:
          image: alpine:latest
          format: spdxtagvalue
          output: tern.spdx
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: ${{ steps.scan.outputs.file}}
