name: build
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v0.2.0
        id: scan
        with:
          image: alpine:latest
          format: json
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: ${{ steps.scan.outputs.file}}
