name: test tern-action

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: philips-labs/tern-action@v0.1.0
      id: scan
      with:
        image: alpine:latest

    - name: cat output
      run: echo ${{ steps.scan.outputs.output }}
