name: build-human
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Running tern action for human output.`
            })
      - uses: philips-labs/tern-action@v1.1.0
        id: scan
        with:
          image: alpine:latest
          format: human
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: ${{ steps.scan.outputs.file}}
