name: build
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v0.1.0
        id: scan
        with:
          image: alpine:latest
      - run: echo "${{ steps.scan.outputs.output }}" > tern.log
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: tern.log
