name: build
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@support-multiple-outputs
        id: scan
        with:
          image: alpine:latest
      - run: echo ${{ steps.scan.outputs.file}}
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: tern.log
