name: build-human
on: 
  push:
  issue_comment:
    types: [created, edited]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@use-versioned-image
        id: scan
        with:
          image: alpine:latest
          format: human
      - uses: actions/upload-artifact@v2
        with:
          name: tern
          path: ${{ steps.scan.outputs.file}}
